### PR TITLE
[BREAKING] [FEAT] Add TypeScript | Bump `actions/checkout` to `v3` & `Node.js` to `v16` | Prettier Formatting

### PR DESCRIPTION
**Pull request by Pranav-yadav**
# Summary

- Bump `Node.js` to `v16`
- Bump `actions/checkout` to `v3`
- Add and set up **TypeScript**
- Refactor to **use Types**
- Add **Prettier formatting** `yarn format-check` and `yarn prettier`
- **Rename** `need-attention.js` to `index.ts`
- Set Up: `yarn build` -> `tsc` -> builds and outputs to `lib/index.js` (`es6`)

>**NOTE**: This will need a major release. i.e. `v2.0.0`

## Changelog

<details><summary>Changelog <sup>(click to expand)</sup></summary>

- Update readme to use `actions/checkout@v3` 2389403 by @Pranav-yadav
- [FEAT] Build needs-attention a0a16ab by @Pranav-yadav
- rm `@octokit/webhooks-definitions` TS 688dd7a by @Pranav-yadav
- Type variables 43886ae by @Pranav-yadav
- Add `@octokit/webhooks-definitions` TS 4a2d2dc by @Pranav-yadav
- Using lib/index.js as main entry-point a1c472e by @Pranav-yadav
- Add `@types/node` 2aa78e2 by @Pranav-yadav
- yarn upgrade c2187cd by @Pranav-yadav
- [FEAT] Use typescript 19be0c8 by @Pranav-yadav
- [FEAT] Add TypeScript ae83988 by @Pranav-yadav
- [BREAKING] Bump `actions/checkout` to `v3` 29d548f by @Pranav-yadav
- [BREAKING] Bump `Node.js` to `v16.0.0` 4d38bf2 by @Pranav-yadav
- Improve logging 3bb1c3a by @Pranav-yadav
- Format :rainbow: f2adeba by @Pranav-yadav
- Delete node_modules :) a783ffa by @Pranav-yadav
- Add prettier formatting 3030978 by @Pranav-yadav
- Add .gitignore :) to ignore node_modules 34b96fe by @Pranav-yadav

</details>

### CODE REVIEW

**Review by hramos — APPROVED** [review]
Thanks for working on this, I'd be okay with merging it in once you're ready.

**Comment by Pranav-yadav** [comment]
> Thanks for working on this, I'd be okay with merging it in once you're ready.

Welcome! Sure, ready to merge.
Actually, I was waiting because I wanted to make sure before release it is tested properly and that there won't be any regression(s).

Edit: Also, one small request from me; please merge all the commits and NOT squash commit merge.
Such that If I need to revert or modify anything I can make use of the commits directly :)

Here's the test (/release) plan:
1. We make sure the build is correct,
2. Publish a **Prerelease** e.g.: `v2.0.0-RC.1`, so we can test before the actual release in actual live env.,
3. Test using the **Prerelease** (`v2.0.0-RC.1`) (using `main.yml`)
4. If everything is fine, publish the `latest` i.e. `v2.0.0`

What do you think @hramos?

P.S.: I would like to follow the release process with you to learn and understand more about the same. Lmk :)

**Comment by Pranav-yadav** [comment]
ping @hramos :)

**Review by hramos — APPROVED** [review]
LGTM - go ahead with plan

**Comment by Pranav-yadav** [comment]
Sure.
Also thanks for inviting me as a collaborator! ❤️

**Comment by Pranav-yadav** [comment]
Merging this PR, and will proceed according to the test & release plan.

**Pull request merged**
